### ISSUE TITLE
iOS Simulator PreProd ortaminda TC Kimlik ve şifre alanlarına tıklanmıyor.

### ISSUE THREAD

**Issue by sermetk** [BKMExpress/BKMExpressXamarinSDK#1]
Androidde sorunsuz tiklanabilirken, ios'ta tiklanmiyor. 

<img src="https://user-images.githubusercontent.com/33116071/97091546-41f40e00-1645-11eb-9a87-568d6ee1b5cb.png" width="250">

**Comment by ensarbayhan** [comment]
Merhaba,

Simulatör menüsünden "IO / Keyboard / Toggle Software Keyboard" seçeneğini seçip klavyenin açık olduğuna emin olduktan sonra uygulamayı kill edip tekrar çalıştırmayı deneyebilir misiniz ? Bu şekilde hatanın giderildiğini tespit ettik.

<img width="867" alt="Screen Shot 2021-02-16 at 21 44 26" src="https://user-images.githubusercontent.com/29458218/108107331-27382000-70a0-11eb-8177-f022d53904a6.png">
